version: '3'
services:
  web:
    build: './web'
    ports:
      - "3000:3000"

  search:
    build: './search'
    ports:
      - "3001:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  cpus:
    build: './cpus'
    ports:
      - "3002:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  gpus:
    build: './gpus'
    ports:
      - "3003:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
  
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "9080:9080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - cpus
      - search
      - gpus
